# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161220_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='confirmation_token',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
    ]
