# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('phase', models.CharField(max_length=30)),
                ('display_name', models.CharField(max_length=50)),
                ('tenant_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('approval_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('examine_number', models.CharField(max_length=100)),
                ('protocol_number', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=255)),
                ('indications', models.CharField(max_length=100)),
                ('category', models.EmailField(choices=[('0', 'Single Center'), ('1', 'Multicenter')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
