# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-30 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('avatar', models.ImageField(upload_to='')),
                ('identity_number', models.CharField(db_index=True, max_length=30)),
                ('identity_country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.EmailField(choices=[('0', 'Principal Investigator'), ('1', 'Doctor'), ('2', 'Nurse Researcher'), ('3', 'Clinical Researcher Associate'), ('4', 'Pharmacist'), ('5', 'Site')], max_length=1, unique=True)),
                ('abbreviation', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Demography',
            fields=[
                ('avatar', models.ImageField(upload_to='')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('0', 'Male'), ('1', 'Female'), ('2', 'Unknow')], max_length=1)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(max_length=50)),
                ('alternate_address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('alternate_phone', models.CharField(max_length=30)),
                ('race', models.CharField(max_length=30)),
                ('ethnicity', models.CharField(max_length=30)),
                ('mrn', models.CharField(max_length=30)),
                ('external_id', models.CharField(max_length=30)),
                ('diagnosis', models.CharField(max_length=30)),
                ('site_name', models.CharField(max_length=30)),
                ('site_code', models.CharField(max_length=30)),
                ('protocol_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='protocol_users.ProtocolUser')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='protocol_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocol_users.ProtocolUser'),
        ),
    ]
